# Generated by Django 2.2.2 on 2019-09-10 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('vendas', '0002_auto_20190910_1708'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItenDoPedido',
            new_name='ItemDoPedido',
        ),
    ]
