# Generated by Django 2.2.2 on 2019-10-16 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_auto_20190910_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': [('setar_nfe', 'usuário pode alterar parametro nf-e'), ('permissao2', 'Permissão 02'), ('permissao3', 'Permissão 03')]},
        ),
    ]
