# Generated by Django 2.2.2 on 2019-10-16 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_auto_20191015_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': [('setar_nfe', 'usuário pode alterar parametro nf-e'), ('ver_dashboard', 'Pode visualizar o Dashboard'), ('permissao3', 'Permissão 03')]},
        ),
    ]
