# Generated by Django 2.2.2 on 2019-10-18 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_auto_20190908_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': [('atualizar_clientes', 'Atualizar clientes')]},
        ),
    ]
