# Generated by Django 2.2.3 on 2019-10-23 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_auto_20191018_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': [('atualizar_clientes', 'Atualizar clientes'), ('excluir_clientes', 'excluir clientes')]},
        ),
    ]
