# Generated by Django 2.2.3 on 2019-10-23 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_auto_20191023_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('atualizar_clientes', 'Atualizar clientes'), ('excluir_clientes', 'excluir clientes'))},
        ),
    ]
